# Introducción {-}

----

La hipótesis reduccionista estipula que un sistema complejo puede ser entendido mediante el estudio de sus partes fundamentales, una idea que parte de la concepción de que todo dentro de nuestro universo está regido por las mismas leyes físicas [@viniegra2014reduccionismo]. Por lo tanto, si todo obedece a las mismas leyes fundamentales, entonces el estudio de los componentes individuales es suficiente para entender el funcionamiento del sistema [@viniegra2014reduccionismo].  Bajo éste enfoque cabría destacar el principio de superposición, mismo que menciona que si un problema puede ser descrito mediante ecuaciones lineales, este se puede descomponer en subproblemas más sencillos, siendo el problema original el resultado de la superposición o suma de estos problemas simples. Por ejemplificar lo anterior, las perturbaciones en la superficie de un estanque pueden describirse como una sumatoria de perturbaciones más pequeñas (provocadas por el viento, objetos cayendo al agua o animales) que se suman para generar un resultado final [@anderson1972more]. Sin embargo, cabe destacar que el enfoque reduccionista no implica *per se* uno construccionista, es decir, que desentrañar las leyes fundamentales del universo no implica necesariamente que podamos reconstruir el universo a partir de las mismas. Este pensamiento resulta insuficiente cuando, a partir de la interacción de los distintos componentes de un sistema, surgen fenómenos que no se pueden predecir basándose únicamente en la consideración de las leyes fundamentales que rigen sus componentes, a lo cual llamamos propiedades emergentes [@anderson1972more].

Al hablar de sistemas complejos y basándose únicamente en las leyes fundamentales de la física, química y biología, resulta problemático predecir la diversidad de comportamientos  que observamos en los organismos vivos, es así como el estudiar una neurona como unidad no permite conocer el fenómeno de la conciencia [@falkenburg2015more]. Un ejemplo de lo anteriormente dicho es el autómata celular llamado *Game of Life*, creado por el matemático John Conway en 1970 [@gardner1970fantastic]. Se trata de un programa que, a partir de dos sencillas reglas que determinaban el estado binario (viva o muerta) de las celdas o células de una superficie bidimensional, y al cabo de un gran número de iteraciones que parten de un estado inicial aleatorio, surgen patrones emergentes que no pueden ser inferidos únicamente a partir de tales reglas [@gardner1970fantastic]. Otros autómatas celulares, como la Hormiga de Langton, también han mostrado el surgimiento de propiedades emergentes conforme tales sistemas dinámicos evolucionan a pasos discretos [@von1966theory].

Los sistemas complejos están formados por elementos o componentes que interactúan entre sí (casi siempre de forma no lineal), y el producto de estas interacciones dan lugar a las llamadas propiedades emergentes, patrones que describen el comportamiento del sistema en su conjunto [@baas1994emergence]. Definimos una propiedad emergente como un fenómeno producto de la interacción de un conjunto de entidades simples que operan en un entorno, dando lugar a comportamientos colectivos más complejos [@lewes1891problems]. En biología, los ejemplos de sistemas complejos son abundantes, desde la forma cómo  distintas biomoléculas interactúan dentro de una célula para conducir señales, las conexiones entre las neuronas y la regulación de la respuesta inmune en el organismo, la propagación de enfermedades infecciosas, la comunicación entre insectos sociales y las relaciones entre las distintas especies que componen un ecosistema [@mason2007graph].

Una red consiste en un conjunto de nodos o elementos que a su vez están conectados por aristas [@mason2007graph]. Las redes de sistemas biológicos a menudo presentan particularidades en su arquitectura, como, por ejemplo, el hecho de que las redes de señalización de una célula sean robustas, donde unos pocos elementos mantienen la mayoría de las conexiones, hace que la red sea poco susceptible a perder funcionalidad ante ataques aleatorios a su estructura [@stelling2004robustness]. Es particularmente importante, por ejemplo, si hablamos de sistemas de regulación génica dirigidos a mantener el funcionamiento de una célula, pues será más probable que un ataque no-dirigido afecte a un componente no esencial de la red, a que interfiera con un elemento que sí lo sea [@stelling2004robustness].

Sin embargo, las redes no suelen ser sistemas aislados, y al igual que sus componentes, las redes interactúan entre sí, generando nuevos fenómenos emergentes a distintos niveles, como sucede con la interacción entre moléculas que a su vez da origen a orgánulos, luego a células, tejidos, órganos, individuos, poblaciones, comunidades, ecosistemas, y así sucesivamente [@liu2011controllability]. El enfoque de estudiar, no solo las interacciones dentro de una red individual, sino también las que ocurren con otras redes, es lo que conocemos como redes multicapa [@liu2011controllability]. Aunque el concepto de las redes multicapa vio la luz dentro del ámbito de las ciencias sociales, este enfoque ha tomado fuerza en distintas ramas del conocimiento, incluyendo a las ciencias biológicas [@zheng2019control]. Las redes multicapa (*multilayer networks*) son un nuevo enfoque que ayuda a comprender fenómenos como la regulación celular a distintos niveles.

Las redes multicapa pueden ser utilizadas para analizar la forma en la cual distintos sistemas interactúan o la forma en la que estos evolucionan en el tiempo [@bianconi2018multilayer]. Uno de estos enfoques son las redes temporales, donde cada capa corresponde a un estado de la red en una fracción determinada de tiempo, por lo que permite visualizar cómo cambia la estructura de dicha red con respecto al tiempo [@bianconi2018multilayer]. Este tipo de enfoque es particularmente útil, por ejemplo, para predecir el comportamiento de una epidemia en una población a pasos discretos, pues la movilidad y, por lo tanto, las interacciones sociales cambian en el tiempo, modificando la forma en que se propaga el agente infeccioso [@zuzek2015epidemic]. Además, existe el caso de sistemas que pueden interactuar a distintos niveles, como los mecanismos de regulación de una célula, donde proteínas pueden interactuar directamente con el DNA o RNAs que pueden bloquear el procesamiento de algunos transcritos. Esto significa que cada una de las capas de la multired puede interactuar con cualquiera de las otras capas y no exclusivamente con las capas continuas [@aleta2019multilayer].

Por su puesto, la microbiota no es la excepción, e investigaciones recientes han revelado que esta es parte de una extensa red que posee un efecto no sólo sobre las mismas poblaciones bacterianas, sino también a nivel de células y tejidos del hospedero, pudiendo tener un impacto importante sobre su fisiología e inclusive sobre la conducta [@albert2002statistical]. El estudio de la microbiota mediante el enfoque de las redes multicapa ha ayudado a comprender el papel e importancia de esta en la salud, así encontrar patrones asociados a enfermedades metabólicas y otros padecimientos [@albert2002statistical].

## Objetivo general {-}

Mediante el uso de redes multicapa, el presente trabajo pretende analizar redes de co-abundancia de OTUs bacterianos procedentes de muestras de la microbiota, empleando este enfoque para comparar la arquitectura de las distintas capas y establecer si existen patrones a través de los cuales se pueda obtener información sobre las características de la microbiota, su dinámica y su relación con el o los huéspedes.

## Objetivos particulares {-}

Estudiar si existen diferencias en la arquitectura de las redes entre las distintas capas.

Identificar comunidades bacterianas dentro de la microbiota que se conserven a lo largo de las capas y analizar si los miembros de dichas comunidades poseen características comunes.

Analizar si existen cambios significativos de las abundancias entre capas y si tales combios pudiesen estar afectando la arquitectura de la red.
