# Antecedentes {-}
----

## Definición y generalidades de una red {-}

Una red se define como un conjunto de elementos o nodos, que denotaré por $V$, que se conectan entre sí mediante aristas  que representaré por el conjunto $E$ [@bianconi2018multilayer]. $G=(V, E)$
Donde $N=|V|$ corresponde al conjunto de nodos que componen la red, y $L=|E|$ al conjunto de aristas que conectan los nodos o vértices [@bianconi2018multilayer].
$$V=\left \{ i|i\in \left \{ 1,2,...,N \right. \right.\left. \left.  \right \} \right \}$$

La información de las conexiones entre los nodos se contiene dentro de una matriz de adyacencia $NxN$, donde se coloca un valor de 1 por cada interacción entre un par de nodos, y de 0 si no existe interacción entre nodos [@bianconi2018multilayer]. En matrices no-dirigidas las matrices son especulares, mientras que en matrices dirigidas esta propiedad se pierde [@newman2006structure].

$$a_{ij}=\left\{\begin{matrix}
1 \space si \space i\leftrightarrow j \\ 
0 \space si \space no.
\end{matrix}\right.$$

$$\begin{matrix}
 & \alpha_{1} & \alpha_{2} & \alpha_{3} & ... & \alpha_{n-1} & \alpha_{n}\\
\beta_{1} & 0 & 1 & 0 & ... & 1 & 1\\
\beta_{2} & 1 & 0 & 1 & ... & 0 & 1\\
\beta_{3} & 0 & 1 & 0 & ... & 1 & 0\\
\vdots & \vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
\beta_{n-1} & 1 & 0 & 1 & ... & 0 & 1 \\
\beta_{n} & 1 & 1 & 0 & ... & 1 & 0
\end{matrix}$$


## Propiedades topológicas de las redes {-}

Cada nodo de la red posee un determinado número de conexiones con otros nodos, una característica que se conoce como degree, y que se define como la sumatoria de todas las interacciones de un nodo con otros nodos de la red [@liu2011controllability].
$$k_i=\sum_{j=1}^{N} a_{ij}$$
Las interacciones entre estos nodos pueden estar o no dirigidas, así como estar o no ponderadas, como veremos a continuación. Se considera que las conexiones de una red son ponderadas, es decir, que poseen un valor numérico asociado a la fuerza de la interacción [@liu2011controllability]. En sistemas biológicos, por ejemplo, esta ponderación podría representarse como la abundancia relativa de algún microorganismo o la correlación entre grado de expresión de dos genes [@bianconi2018multilayer].
$$k_i=\sum_{j=1}^{N} \theta (a_{ij})$$
Las conexiones de las redes pueden ser  dirigidas, es decir, la conexión del nodo $i$ con $j$ no establece de forma implícita la conexión del nodo $j$ al $i$ [@bianconi2018multilayer]. Algunos ejemplos de redes no-dirigidas son las redes de regulación transcripcional o las redes de regulación por microRNA-transcritos, donde si un elemento $x$ está regulando positiva o negativamente a un elemento $y$, no implica que $y$ también regule a $x$. También podríamos destacar redes sociales como twitter, donde si un individuo sigue a otro no implica que ese otro individuo siga al primero.

Las redes no-dirigidas asumen que la interacción es bidireccional, algo que no ocurre necesariamente en las redes dirigidas, por lo que en este segundo caso la matriz de adyacencia es asimétrica [@bianconi2018multilayer].

$$k_{i, in}=\sum_{j=1}^{N} \theta (a_{ji})$$
$$k_{i, out}=\sum_{j=1}^{N} \theta (a_{ij})$$
El coeficiente de clusterización o de transitividad cuantifica la densidad de triángulos que se forman entre los vecinos de un nodo $i$, lo cual se puede interpretar como la probabilidad de que un nodo esté interconectado con otros [@wang2017comparison]. Para una red no dirigida, el coeficiente de clusterización se calcula de la siguiente forma.
$$C_{i}=\left\{\begin{matrix}
\frac {2*(numero \space de \space triangulos \space pasando \space por \space el \space nodo \space i)}{k_{i}(k_{i}-1)} \space para \space k_{i}>1\\
0 \space para \space k_{i}=1 \space o \space 0
\end{matrix}\right.$$
Un coeficiente de transitividad igual a 0 significa que los nodos que interactúan con el nodo $i$, no están conectados entre sí, por lo que este valor aumenta entre mayor sea la conectividad de los nodos vecinos [@schaeffer2007graph]. Un coeficiente de transitividad cercano a 1 implica que los nodos están estrechamente conectados en la región analizada, y, por lo tanto, que conforman un clúster o conjunto dentro de la red [@schaeffer2007graph]. En sistemas biológicos, como en una red de distintos genes, regiones con un coeficiente de clusterización alto podría indicar que los genes analizados estarían posiblemente involucrados en un proceso biológico común [@aleta2019multilayer].

![**Figura 1:** Las redes generadas aleatoriamente (izquierda) tienden a tener un coeficiente de clusterización significativamente menor al de las llamadas redes de mundo pequeño (derecha), con el mismo número de nodos. Las redes de mundo pequeño se caracterizan por tener conjuntos de nodos estrechamente interconectados, a pesar de que la mayoría de sus elementos no sean vecinos entre sí [@schaeffer2007graph].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig1.png)

El coeficiente de clusterización es una propiedad local, es decir, para cada nodo se define un valor de dicho coeficiente. Para determinar un valor global del coeficiente de clusterización  de la red en su conjunto es simplemente el promedio aritmético de todos los coeficientes de clusterización.

$$C_{net}=\frac{1}{N}\sum_{i=1}^{N} C_{i}$$
Al tipo de redes donde la mayoría de los nodos no son vecinos entre sí se les conoce como redes de mundo pequeño. Los primeros en idear este coeficiente fueron Watts y Strogatz en 1988, y es gracias a esta propiedad que es posible diferenciar una red aleatoria de una red de mundo pequeño [@watts1998collective].

![**Figura 2:** La aleatoriedad de una red ($p$) es un factor importante en su arquitectura. Cuando este valor es igual a cero, los nodos poseerán exactamente el mismo número de conexiones y, por lo tanto, la distribución de su *degree* será uniforme. Por el contrario, cuando los valores de aleatoriedad son cercanos a uno, dicha distribución se asemeja a una curva gaussiana, donde existirán nodos que posean muchas conexiones en un extremo de la distribución, otros con un número bajo de conexiones y la mayoría con un número de conexiones cercano a la media de la red [@watts1998collective].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig2.png)

![**Figura 3:** Conforme aumenta la aleatoriedad de una red, el coeficiente de clusterización ($C(p)$) adquiere valores cada vez menores; al tiempo que la longitud de la red ($L(p)$), es decir, la distancia (cuantificada en número de aristas) más corta entre todos los posibles pares de nodos de una red, también disminuye [@watts1998collective].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig3.png)

Esta característica le brinda a la red robustez, es decir, la capacidad de conservar su arquitectura ante ataques aleatorios [@newmanoxford]. En sistemas biológicos, como pueden ser cascadas de señalización, de suceder mutaciones aleatorias que puedan alterar el funcionamiento normal de alguna proteína involucrada en determinada ruta de señalización, es estadísticamente más probable que dicha mutación ocurra en un elemento de la red con bajo número de conexiones a que suceda en algún elemento central de la red, lo cual permite que la célula pueda continuar sus funciones biológicas con relativa normalidad [@das2020small]. En este tipo de redes unos pocos nodos poseen la mayor parte de las conexiones, mientras que la mayoría de los nodos poseen un bajo número de estas [@newmanoxford].

![**Figura 4:** La importancia de un nodo dentro de la red está determinada por su centralidad, misma que se puede determinar bajo distintos métodos. A) A aquellos nodos con una alta centralidad se les conoce como *hubs* o conectores. B) La centralidad por *degree* o grado se fundamenta en el número de conexiones de los nodos, mientras que la centralidad por intermediación o *betweenness* otorga mayor peso a nodos que actúan como puentes entre clústers separados. La centralidad por *closeness* o cercanía cuantifica el promedio de las distancias más cortas de cada nodo con todos los demás.  La centralidad por eigenvectores, también conocida como *eigencentrality*, es una medida autorreferencial de centralidad que prima la calidad de las conexiones, donde un nodo tendrá mayor relevancia si a su vez está conectado a un nodo con alta centralidad. El coeficiente de partición, por su parte, considera la distribución de las conexiones entre clústers separados. Finalmente, el *PageRank* es una medida de centralidad similar al *degree* pero empleada en redes dirigidas, y a menudo usada para determinar la importancia de páginas web [@farahani2019application].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig4.png)

Sin embargo, los sistemas biológicos no suelen ser entes aislados, sino que se ven afectados por su interacción con aquello que los rodea. La idea de que los componentes de una red son capaces de interactuar o relacionarse de alguna forma con los elementos de otras redes, nos adentra en el concepto de las redes múltiples (*multinetworks*), también conocidos como multigrafos (*multigraphs*) o redes multicapa (*multilayer networks*).

## Definición y características de las redes multicapa {-}

Una red multicapa es una red compuesta por $M$ redes individuales cuyos elementos interactúan entre sí, constituyendo cada una de estas redes individuales una capa [@buldyrev2010catastrophic].

$$\cal{M}=\mathrm{(Y,\vec{G},\cal{G})}$$

Donde $Y$ corresponde al conjunto de capas:

$$Y=\left \{ \alpha | \alpha \in \left \{ 1, 2, ... \space ,M \right \} \right \}$$

$\vec{G}$ corresponde a la lista ordenada de redes que conforman cada una de las capas, donde cada elemento $G_{\alpha}=(V_{\alpha}, E_{\alpha})$ es una red monocapa con sus propios nodos y aristas dentro de la red multicapa [@buldyrev2010catastrophic].

$$\vec{G} = (G_{1}, G_{2}, ... \space , G_{\alpha }, ... \space , G_{M})$$

Por su parte, $\cal{G}$ representa a una matriz $MxM$ en la cual están contenidas las interacciones entre los nodos de cada par de redes que conforman la red multicapa. Debido a que en la matriz están representadas las interacciones entre cada par de redes, podemos entender el total como un conjunto de redes bipartitas [@buldyrev2010catastrophic].

$$\cal{G} = (V_{\alpha},V_{\beta},\mathit{E_{\alpha, \beta}} )$$

Las redes multicapa se clasifican en tres categorías principales: las redes multiplex, redes temporales y redes formadas por redes [@bianconi2018multilayer]. Las redes multiplex son el ejemplo más sencillo de redes multicapa; estas se emplean generalmente cuando el mismo conjunto de nodos se encuentra contenido en las distintas capas, pero la interacción entre estos es distinta en cada una [@bianconi2018multilayer]. Las redes múltiplex son empleadas para mostrar cómo un mismo conjunto de elementos pueden interactuar entre sí de distintas formas, por lo general, asociando las aristas con un color distinto para cada tipo de interacción [@kanawati2015multiplex]. Por ejemplo, podríamos ejemplificar esto como un conjunto de individuos que se relacionan entre ellos por medio de distintas redes sociales [@aleta2019multilayer]. En biología, por ejemplo, podríamos construir una red multiplex donde una capa representa las correlaciones entre la expresión de distintos genes y otra capa representa las interacciones entre las proteínas que estos mismos genes codifican [@arda2019multiplex].

Tomando como referente el último ejemplo, podemos también aludir al problema de los sistemas dinámicos. Los sistemas dinámicos son aquellos donde las interacciones cambian constantemente en función del tiempo, y, por lo tanto, la forma en que sus componentes están relacionados depende en gran medida del momento y las condiciones en las cuales se realiza la medición [@holme2012temporal]. Los sistemas biológicos son por lo general sistemas dinámicos, pues estos están constantemente sometidos a cambios debidos a estímulos con el ambiente que los rodea, así como a la naturaleza cambiante de los procesos que ocurren dentro de las células. Por ejemplo, un conjunto de genes no permanecerá siempre expresado de la misma manera, sino que la expresión de estos dependerá de un gran número de estímulos. Este tipo de sistemas se pueden representar mediante redes temporales, donde cada una de las capas representa una captura de las interacciones entre un conjunto de nodos en un momento determinado [@holme2012temporal]. Las redes temporales son secuenciales, es decir, que las capas están ordenadas de modo que se suceden una detrás de otra, por lo cual una capa $t_{i}$ solo puede interactuar con la capa siguiente $t_{i+1}$ [@barrat2008dynamical]. Este tipo de redes son similares a las redes multiplex en el sentido de que se trata del mismo conjunto de nodos entre las capas, aunque conforme avanza el tiempo nodos nuevos pueden integrarse a la capa siguiente mientras que otros dejan de estar presentes [@barrat2008dynamical].

Finalmente podemos destacar las redes formadas por redes. Estas poseen importantes diferencias con respecto a los tipos de redes ya mencionados, empezando con que los nodos varían entre capa y capa; además de que los nodos de una capa no interactúan necesariamente solo con las capas adyacentes, como sí sucede con las redes multiplex o las redes temporales, sino que pueden interactuar con cualquier número de nodos en cualquiera de las capas [@kenett2015networks].

![**Figura 5:** Existen distintos tipos de redes multicapa, de las cuales podemos resaltar tres categorías. a) Las redes multiplex se caracterizan por mantener el mismo conjunto de nodos en sus distintas capas. Este tipo de redes suele emplearse para representar cómo los elementos de un conjunto interactúan entre sí de distintas formas o bajo distintas condiciones. b) Las redes temporales se usan para representar la forma en que un conjunto de elementos o nodos interactúa en función del tiempo. A diferencia de las redes multiplex, las capas de las redes temporales son secuenciales y se suceden de forma ordenada una tras otra, representando cada una las interacciones entre los distintos nodos a distintos “momentos” de un intervalo de tiempo definido. Estas son útiles para representar sistemas dinámicos, donde las interacciones entre sus componentes cambian continuamente. c) En las redes conformadas por redes, por su parte, las interacciones entre los elementos de una capa no están limitadas a las de las capas vecinas, sino que los nodos de cada capa pueden poseer un número de conexiones con los nodos de cualquiera de las capas de la red múltiple [@bianconi2018multilayer].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig5.png)

Debido a que las interacciones entre capas de una red multiplex están limitadas a las capas vecinas con respecto a la capa de referencia, podemos representar a una red múltiplex como una red bidimensional con conexiones de distintos tipos. En este tipo de redes los nodos de una capa solo se conectan con sus homólogos en la siguiente, además de que el conjunto de estos se mantiene en las distintas capas, variando solo las interacciones entre los nodos dentro de las mismas capas [@kanawati2015multiplex].

![**Figura 6:** Las redes multiplex muestran cómo los nodos de una red pueden interactuar entre sí de distintas formas. En este ejemplo se muestran los vínculos matrimoniales y de negocios entre distintas familias nobles florentinas del siglo XV. Utilizando esta representación, podemos vislumbrar con facilidad el papel central que tenía la familia Medici tanto en el ámbito comercial como político entre la nobleza florentina [@padgett1993robust].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig6.png)

$$\cal{M} = \mathit{(Y,\vec{G})}$$
Donde
$$\vec{G} = (G_{1}, G_{2}, ... \space ,G_{\alpha}, ... \space ,G_{M})$$

Cada una de las capas de la red multiplex poseen la misma cantidad de nodos
$$V = \left \{ i|i \in \left \{ 1,2,...,N \right \} \right \}$$

Sin embargo, a pesar de que las redes multiplex presentan el mismo grupo de nodos en las distintas capas, a menudo es necesario distinguir la capa en la cual se encuentra cada uno de los nodos [@bianconi2018multilayer].
$$V = \left \{ i_\alpha |i \in \left \{ 1,2,...,N \right \} \right \}$$

Tanto para redes múltiplex como para redes temporales, la conexión de los nodos entre capa y capa está dada por la delta de Kronecker. Esta es una función cuya variable puede adquirir un valor de 1 en aquellos casos donde un elemento sea igual en dos conjuntos, o en este caso en dos capas, y de 0 cuando son diferentes. Aquellos nodos que cumplen la condición de ser equivalentes entre una capa y otra se denominan nodos réplica [@gomez2013diffusion].

$$\delta _{ij} = \left\{\begin{matrix}
1 \space si  \space i=j \\ 
0 \space si  \space i\neq j
\end{matrix}\right.$$

Como hemos visto previamente, la información de una red simple está contenida dentro de una matriz de adyacencia, sin embargo, en redes multicapa este modelo resulta insuficiente para contener la información de estas estructuras, razón por la cual empleamos las llamadas matrices de supra-adyacencia. Este tipo de matrices están compuestas a partir de múltiples matrices de adyacencia individuales, y contiene tanto la información referente a las interacciones dentro de las capas como las interacciones entre capas [@cozzo2016multilayer].

![**Figura 7:** A la derecha se muestra la representación tridimensional de una red bipartita. La matriz de supra-adyacencia ($\bar{A}$) está compuesta a partir de la fusión de dos matrices de adyacencia simples. La primera es la matriz $A$, que codifica las interacciones de los nodos dentro de las capas, mientras que la matriz $C$ contiene las interacciones entre las capas [@cozzo2016multilayer].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig7.png)

Como se puede inferir, las propiedades de las redes múltiples difieren de las redes simples. Como ya hemos visto, el *degree* ($k_{i}$) de un nodo de una red simple es un escalar, un número entero positivo que representa el número de conexiones de un nodo. En redes múltiples este valor está representado en un vector M-dimensional que contiene los valores del *degree* de un nodo “$i$” a lo largo de las $M$ capas de la red [@iacovacci2016functional].

$$k_{i} = (k_{i}^{[1]}, k_{i}^{[2]},..., k_{i}^{[M]})$$
Al igual que como sucede con redes simples, la distribución del *degree* es una función de probabilidad $P^{[a]}(k)$. En redes múltiples, esta función de probabilidad se define de forma independiente para cada capa [@iacovacci2016functional].

$$P^{[a]}(k) = \frac{N^{[a]}(k)}{N_{a}}$$
El coeficiente de clusterización en una red multiplex, al igual que sucede con las redes simples, permite conocer si existen conjuntos donde varios nodos están interconectados entre sí, sólo que, en este caso, esto también incluye las conexiones que se generan entre las capas [@lancichinetti2012consensus]. En redes sociales, por ejemplo, esta propiedad permitirá conocer la probabilidad de que dos individuos realicen varias actividades juntos, o que dos personas en dos clases distintas tengan algún amigo en común [@bianconi2018multilayer]. En biología, por ejemplo, el coeficiente de clusterización podría emplearse para saber si dos genes que se sobreexpresan en distintos pacientes analizados, podrían estar involucrados en el mismo proceso [@zuzek2015epidemic]. El problema de la clusterización en redes múltiples es que los ciclos de longitud, los mismos que generan triángulos de nodos interconectados en redes simples, se completan en capas distintas, lo que complica su identificación [@lancichinetti2012consensus].

![**Figura 8:** En el extremo izquierdo de la imagen se muestra una red simple donde los dos vecinos del nodo $i$ (marcado en rojo), están conectados entre sí. En los siguientes tres diagramas se muestran ejemplos de redes bipartitas donde, con respecto a la capa donde se encuentra el nodo $i$, un grupo de nodos pueden no ser vecinos en dicha capa, pero si en una capa distinta, permitiendo la formación de ciclos entre ambas capas. En el extremo derecho de la imagen podemos ver un ejemplo en el cual se ejemplifica cómo estos ciclos de nodos interconectados no necesariamente se limitan a dos capas, sino que pueden extenderse a más capas [@cozzo2013clustering].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig8.png)

De forma similar a como hemos visto en redes simples, podemos obtener este coeficiente dividiendo el número de triángulos que se forman entre los nodos de distintas capas sobre el producto del número de vecinos (*degree*) de la primera y última capa ($N_{\alpha, \gamma}$) [@cozzo2013clustering].

$$C_{i}^{[\alpha,\beta,\gamma]}=\frac{\sum_{r,s}a^{[\alpha]}_{ir}a^{[\beta]}_{rs}a^{[\gamma]}_{si}}{N_{\alpha, \gamma}}$$

Donde:

$$N_{\alpha, \gamma} = \left\{\begin{matrix}
k^{[\alpha]}_{i}k^{[\gamma]}_{i} \space para \space  \alpha \neq \gamma \\
k^{[\alpha]}_{i}(k^{[\alpha]}_{i}-1) \space para \space  \alpha = \gamma
\end{matrix}\right. $$

Así como sucede en lo referente a la transitividad, la cuantificación de otras propiedades de la red, tales como las distancias entre los nodos, difieren cuando tratamos con redes multicapa. Inferir la distancia más corta entre cualquier par de nodos implica ahora considerar las distancias entre capas $(\psi_{ij})$, además de las distancias más cortas dentro de la misma capa $(\sigma_{ij})$. La fracción resultante nos permite conocer la accesibilidad entre los nodos, una propiedad a la cual denominamos interdependencia ($\lambda_{i}$), cuyo valor fluctúa entre 1 y 0 [@donges2011investigating].

$$\lambda_{i} = \sum_{i \neq j}\frac{\psi_{ij}}{\sigma_{ij}}$$

La interdependencia media de la red multicapa puede expresarse como:

$$\lambda = \frac{1}{N}\sum_{i=1}^{N}\lambda_{i}$$

Cuando $\lambda$ posee un valor equivalente o muy cercano a 0, significa que existe una muy baja interdependencia entre las capas, ya que todas o la gran mayoría de las rutas más cortas entre cualquier par de nodos se encuentran dentro de la misma capa. Lo contrario sucede cuando $\lambda$ adquiere valores cercanos o equivalentes a 1, la interdependencia de los nodos entre las capas es muy alta [@donges2011investigating].

El análisis de las propiedades de la red puede arrojar indicios sobre el comportamiento del sistema en su conjunto, así como información que ayude a explicar ciertos fenómenos que ocurren cuando estudiamos ejemplos reales de sistemas complejos.


## Aplicaciones de las redes multicapa {-}

Las redes multicapa representan un enfoque relativamente nuevo en teoría de redes y en el análisis de sistemas complejos. Los sistemas complejos son aquellos que están compuestos por un número muy grande de distintos elementos que interactúan, de forma no lineal,  entre sí [@liu2016control]. A medida que el estudio de este tipo de sistemas avanzaba, fue evidente pronto que no se trataba de sistemas aislados, y que, por el contrario, se requería de una nueva perspectiva que ampliara nuestra capacidad para analizarlos, dando lugar al enfoque de las redes multicapa [@bianconi2018multilayer]. Las redes multicapa son ubicuas, podemos encontrar ejemplos en casi todo aquello que nos rodea; desde la evolución de las conexiones neuronales con respecto al tiempo, las interacciones entre el proteoma, el genoma y el transcriptoma, hasta el internet, los medios de transporte urbano en una ciudad o las interacciones entre las distintas partículas elementales [@bianconi2018multilayer].

![**Figura 9:** Mediante el análisis de las propiedades de las redes múltiples a gran escala es posible obtener información sobre el comportamiento de un sistema. En el ejemplo se realizó la simulación de un modelo basado en el sistema de transporte de Zaragoza, España. a) Distribución del número de veces que los individuos pudieron llegar a su destino en el intervalo de tiempo en que se realizó la simulación. b) Distribución del tiempo de espera, la distancia recorrida y la duración del recorrido empleando dos velocidades de movimiento distintas ($\delta$). c) Fracción de pasajeros que usaron las distintas líneas de transporte. Este tipo de simulaciones se ha empleado para buscar alternativas que permitan mejorar la eficiencia de un sistema de transporte público [@aleta2017multilayer].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig9.png)

En sistemas complejos, estas interacciones dan lugar a propiedades emergentes, cualidades o características sólo discernibles a macroescala pero que no pueden ser predichas únicamente mediante el estudio de las partes constituyentes de la red, patrones que sólo pueden conocerse cuando se observa el resultado de la interacción de  sus partes constituyentes. Los ejemplos de propiedades emergentes son variados, tales como la conciencia o la inteligencia, producto de las billones de interacciones entre neuronas [@o1994emergent] nuestras sociedades, en donde la formación de naciones puede considerarse como  una propiedad emergente de la interacción humana [@lazega1999multiplexity]; los organismos como producto de la interacción entre millones de células; o los organismos mismos como parte de un ecosistema [@liu2016control]. En cualquiera de estos casos, el estudio de una sola neurona como unidad no permitiría comprender a la conciencia humana, así como el estudio de un solo individuo no permitiría predecir el comportamiento de una civilización, o el de una célula el comportamiento de todo un organismo vivo formado por millones de estas. En cualquier caso, la comprensión de un sistema complejo requiere el análisis de su estructura y comportamiento en su conjunto, sin embargo, la interacción de los elementos de una red no se limita necesariamente a los elementos dentro de la red, una idea que posteriormente dio paso al concepto de redes multicapa [@bianconi2018multilayer].

Aunque las redes multicapa se estudiaron originalmente en el contexto de las ciencias sociales con el fin de representar la forma en que distintas personas establecen lazos de formas diferentes, por ejemplo, a través de las relaciones laborales, de amistad o mediante distintas redes sociales [@lazega1999multiplexity]; el uso de este enfoque se ha extendido a muchos otros campos, y las ciencias biológicas no han sido la excepción. Desde la neurociencia y la biología molecular hasta la ecología y la epidemiología, las redes multicapa han tenido multitud de aplicaciones dentro del campo de la biología y la medicina.

![**Figura 10:** Una de las aplicaciones más recurrentes en biología de las redes multicapa es en el campo de la epidemiología, en donde se aplican redes temporales para predecir el comportamiento de un brote infeccioso en una población. En el ejemplo se muestra una representación de un modelo susceptible-infectado-susceptible (SIS), donde la interacción entre los individuos propicia que un nodo cambie su estado como susceptible a infectados o nuevamente susceptibles en la siguiente capa, dependiendo de su estado anterior. Además, en este tipo de modelos los individuos cambian su interacción en el tiempo, y la probabilidad de que un individuo pase de un estado al otro depende de una determinada tasa de cambio [@sanz2014dynamics].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig10.png)

Podemos aludir al ejemplo de las redes entre genes, mismas que a su vez producen proteínas cuya interacción genera un efecto en las células, a la vez que regulan el sistema a distintos niveles. (genoma, epigenoma, transcriptoma, proteoma y metaboloma). A este conjunto de biomoléculas en interacción que constituyen una célula es a lo que llamamos interactoma [@aleta2019multilayer]. Una proteína producida por determinado gen puede regular positiva o negativamente a otro gen al realizar una modificación epigenética sobre este, así como un siRNA es capaz de regular la traducción a proteína de determinado transcrito. Como podemos ver con este ejemplo, la regulación de la red puede ocurrir a distintos niveles y mediante la interacción de elementos de alguna capa con cualquiera de las otras capas [@sun2016integrative].

![**Figura 11:** La regulación de las respuestas celulares a los estímulos ambientales puede darse a distintos niveles, desde la expresión de génica, la traducción de transcritos o la actividad de las proteínas. Las alteraciones en los mecanismos de regulación del organismo se han asociado a múltiples enfermedades, y nos han permitido profundizar nuestro conocimiento al respecto de estas [@sun2016integrative].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig11.png)

El análisis del interactoma mediante redes multicapa también ha sido útil para comprender los efectos de fármacos en los complejos procesos que ocurren dentro de una célula, pues integra los distintos niveles de regulación celular y la forma en que estos se ven alterados en respuesta a determinado medicamento [@aleta2019multilayer]. De igual modo, ciertos patrones de expresión génica anormales se han asociado a distintos tipos de cáncer o a enfermedades crónico-degenerativas [@albert2002statistical].

El mapeo de redes cerebrales mediante redes temporales ha adquirido gran importancia también. Las redes multicapa permiten representar detalladamente las interacciones sinápticas entre neuronas y su evolución ante estímulos. La gran mayoría de los estudios al respecto se han centrado en *C. elegans*, un nemátodo que ofrece numerosas facilidades al momento de estudiar su sistema nervioso, pues además de ser un modelo de estudio ampliamente conocido, también posee un número reducido y limitado de neuronas. Se han empleado redes múltiples para analizar la señalización aminérgica y neuro peptídica entre las 302 neuronas de *C. elegans*, asociando una capa distinta para cada neurotransmisor involucrado en la comunicación sináptica [@bentley2016multilayer]. En humanos el enfoque de las redes múltiples se ha empleado para estudiar las relaciones entre distintas zonas del cerebro y las respuestas cerebrales en reposo mediante procedimientos no invasivos, tales como la resonancia magnética [@del2016synchronization].

En ecología, el enfoque de las redes multicapa ha sido de suma utilidad para comprender las interacciones entre los distintos organismos que componen un ecosistema. La construcción de redes tróficas no solo ha permitido comprender mejor el flujo de materia y energía dentro de un ecosistema, sino también la importancia de las relaciones simbióticas y cómo estas afectan la estabilidad del ecosistema y las poblaciones, por ejemplo, la relación entre las plantas angiospermas y los insectos polinizadores [@schleuning2020trait]. Dentro de las redes tróficas se consideran distintos factores, incluyendo el peso o fuerza de la interacción y el tipo de esta (mutualismo, amensalismo, parasitismo, comensalismo, depredación, etc.), pudiendo representar los distintos tipos de interacción en una red tipo multiplex [@schweiger2008climate].

El análisis mediante redes temporales ha arrojado información sobre el cambio de las interacciones entre organismos en respuesta al cambio climático, a la deforestación o a la contaminación. La reducción de la biodiversidad debida directa o indirectamente a la actividad humana altera la estructura de la red, provocando también cambios en poblaciones de organismos relacionados con aquellos cuyas poblaciones se han alterado debido a la actividad humana [@schweiger2008climate]. Se ha observado que la extinción de ciertas especies ha provocado también la caída de las poblaciones de otras especies relacionadas con las primeras, o, por el contrario, sus poblaciones aumentan exponencialmente, derivando en el fenómeno de las plagas [@ludwig1978qualitative]. También se han empleado redes temporales para estudiar el comportamiento de animales sociales, tales como hormigas, y la forma en que estos lazos sociales ayudan al éxito de las comunidades en general [@schleuning2020trait].

![**Figura 12:** En un ecosistema se dan múltiples interacciones entre distintos organismos. La estabilidad del ecosistema en sí mismo, depende en gran medida de estas interacciones, pues la extinción de una especie puede conllevar a extinciones secundarias de especies que, en mayor o menor medida, dependían de las poblaciones de la primera especie. En el ejemplo se muestran plantas con flores que dependen de aves como polinizadoras y viceversa. Algunas especies con relaciones mutualistas han evolucionado para adaptar sus características para facilitar la interacción entre ellas, en este caso la forma de las flores o del pico en sus respectivos casos; sin embargo, esto provoca que ambas especies sean más interdependientes entre sí, y, por lo tanto, más proclives a extinguirse en el caso de que la población de cualquiera de las dos especies entre en declive o se extinga. En ocasiones, la entrada de alguna especie exógena al ecosistema puede suplir la función de la especie extinta y favorecer la recuperación de las poblaciones de su simbionte, sin embargo, con frecuencia la introducción de nuevas especies puede tener un efecto contrario al provocar el desplazamiento por competencia de las especies nativas [@schleuning2020trait].](C:/Users/LaV_V/OneDrive/Documentos/Tesis/Images/fig12.png)


## Inferencias de redes {-}

Hemos visto que la creación de redes temporales y redes multiplex es posible mediante la delta de Kronecker, dicha función  permite conectar los nodos de una capa con sus respectivos nodos réplica en las capas adyacentes. Sin embargo, al intentar construir las redes de cada capa nos encontramos con un problema: Construir una red a partir de los datos experimentales. Como solución se han propuesto numerosos algoritmos que llevan a cabo la tarea de inferir las posibles asociaciones entre los componentes de una red partiendo de las abundancias de secuencias en las muestras, mismas que pueden asociarse a OTUs o transcritos de genes.

Para identificar la presencia de algún microorganismo o la expresión de algún gen a partir de una muestra se emplean métodos de amplificación de ácidos nucleicos, tales como el PCR o el RT-PCR, con el fin de identificar secuencias específicas. A partir del análisis de estas secuencias se obtienen las abundancias relativas, mismas que pueden interpretarse como el volumen de las secuencias identificadas en una muestra [@villaintroduction].

