# Materiales y métodos {-}

----

Previamente hemos analizado las posibilidades y limitaciones de las redes multicapa, así como el procedimiento que implica su inferencia y construcción. Para la realización de este trabajo se utilizó la versión 4.1.0 (2021-05-18) de R. Se emplearon los paquetes *igraph*, *phyloseq*, *devtools*, *SpiecEasi*, *seqtime*, *muxViz* y *multinet*. Algunos de los paquetes están disponibles en CRAN y pueden ser descargados mediante el comando *install.packages()* de R, pero otros fueron descargados de repositorios de GitHub o del proyecto para análisis de datos genómicos Bioconductor.

Paquete | Uso | Fuente | Descarga
--------|-----|--------|---------
igraph | Construcción, diseño, análisis y manipulación de redes. | CRAN | install.packages("igraph")
phyloseq | Herramientas para la importación, análisis, almacenamiento y la visualización de datos de microbioma. | Bioconductor | if(!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager"); BiocManager::install("phyloseq")
devtools | Provee las funciones necesarias para el desarrollo de paquetes de R y descarga desde repositorios GitHub. | CRAN | install.packages("devtools")
SpiecEasi | Estimación de la covarianza de datos de abundancia e inferencia de redes ecológicas. | GitHub | library(devtools); install_github("zdk123/SpiecEasi")
seqtime | Provee datos de series temporales de microbiota, y herramientas para simular y analizar la dinámica de comunidades microbianas en el tiempo. | GitHub | library(devtools); install_github("hallucigenia-  sparsa/seqtime")
muxViz | Construcción, diseño y análisis de redes multicapa. | GitHub | devtools::install_github("manlius/muxViz")
multinet | Construcción, diseño y análisis de redes multicapa. | CRAN | install.packages("multinet")
corrplot | Análisis de la correlación de matrices. | CRAN | install.packages("corrplot")

