# Discusión {-}

## Discusión de la red escarabajo-solanácea {-}

La relación de *Lema daturaphila* y las especies del género *Datura* es ampliamente conocida, puesto que dicho escarabajo es considerado como una plaga para múltiples especies de dicho género. A pesar de que *Datura inoxia* sea una planta tóxica para la mayoría de insectos herbívoros, este escarabajo se ha adaptado para alimentarse de dicha planta solanácea. Las larvas del escarabajo se alimentan de las hojas de la planta durante el verano, y a menudo se les puede encontrar concentradas en grandes grupos en la superficie de las hojas [@goldberg2020towards]. Sin embargo, nuestro conocimiento sobre el papel de la microbiota en la relación entre ambas especies y su interacción con sus respectivos huéspedes, es aún muy limitado.

Todos los análisis revelaron una amplia presencia del *phylum* Proteobacteria, un clado que sin embargo es muy diverso y, por lo tanto, difícil de asociar a una única función concreta. Su relación con la planta y el insecto varía a lo largo de un espectro muy amplio que incluye especies comensales, patógenas, simbiontes y bacterias de vida libre.

Dentro de este marco cabría señalar a las alfa-proteobacterias, algunas de las cuales suelen estar asociadas a tejidos vegetales como bacterias fijadores de nitrógeno, un papel que también desempeñan varias especies de beta-proteobacterias, clase que, sin embargo, no se encontró en proporciones significativas. Algunas de las alfa-proteobacterias identificadas, tales como *Skermanella* y *Microvirga*, se encuentran en una gran variedad de hábitats, especialmente en el suelo [@del2019soil], lo que en primera instancia nos llevaría a plantear la hipótesis de que se trata de bacterias de vida libre. Sin embargo, el hecho de que estas se concentran casi exclusivamente en las muestras de epífitas sugiere una relación simbiótica o de comensalismo.

En el caso de *Sphingomonas* y *Methylobacterium*, ambos son géneros de bacterias fijadoras de nitrógeno, el primero de los cuales suele ser más abundante en las raíces de las plantas, mientras que en el género *Methylobacterium* podemos encontrar simbiontes endófitas como *Methylobacterium symbioticum*, y simbiontes epífitas como *Methylobacterium extorquens* [@fausto2018olive], aunque en las muestras analizadas solo se encontraron en las muestras de epífitas. Esto sugiere que la alta abundancia relativa de alfa-proteobacterias en las muestras, especialmente de *Skermonella* debido a su sobresaliente presencia, podría estar relacionado con una asociación de tipo mutualista o comensal, como bacterias fijadoras de nitrógeno, con los tejidos superficiales de la solanácea.

Lo anterior contrasta con la mayor diversidad encontrada en las muestras del escarabajo. En dicho caso, la presencia de bacterias particularmente abundantes en heces e intestinos, como *Serratia*, *Pseudomonas*, *Siccibacter*, *Pantoea* y *Salmonella*, también en muestras huevos, podría explicarse debido a que las larvas suelen cubrirse de excremento como mecanismo protector contra los depredadores [@visakorpi2021does]. Este fenómeno también podría explicar por qué se encontraron estas mismas bacterias en la superficie de la planta a pesar de estar fuertemente asociadas al intestino del escarabajo. Algunas de estas bacterias podrían estar involucradas en la digestión, pero también en la protección contra patógenos, como sucede con *Serratia symbiotica* y su asociación con los áfidos, lo que le otorga a este último protección contra parásitos [@renoz2019evidence]. Esta hipótesis se ve fomentada ante el hecho de que *Serratia* junto a *Pseudomonas* son los géneros más abundantes en las muestras, y están ampliamente distribuidas en todos los tejidos analizados del insecto.

El análisis mediante redes multicapa identificó conjuntos de bacterias que podrían, dados los datos arrojados por los análisis, tener una función biológica importante en la regulación de la propia red y algunos incluso podrían actuar como simbiontes de sus huéspedes. Sin embargo, se requiere compaginar esta información con una base de datos de modo que podamos categorizar y etiquetar los nodos, e identificar si las funciones comunes asociadas a los OTUs se corresponden con los *clusters* hallados.

## Discusión de las redes temporales de los sujetos A y B {-}

La microbiota intestinal humana es sumamente estable. A pesar de la constante variación en las abundancias de las poblaciones bacterianas a lo largo del tiempo, la mayor parte de estas poblaciones tiende a mantenerse dentro de un rango, independientemente de las constantes perturbaciones derivadas de la ingesta de alimentos, medicamentos, actividad física, entre otros factores involucrados [@costello2009bacterial]. Enfatizando lo anterior, un estudio de Caporaso *et al.* (2011) calculó que alrededor del 95% de los OTUs bacterianos encontrados en muestras de intestino y saliva, permanecieron en rangos estables a lo largo del periodo de muestreo, correspondiente a un año [@caporaso2011moving]. En general, a pesar de las constantes fluctuaciones en las poblaciones bacterianas a lo largo de una serie de tiempo, estas tienden a aproximarse a determinados valores de equilibrio que dependen en gran medida de sus interacciones con otros OTUs bacterianos, lo que mantiene la estabilidad de las comunidades. Sin embargo, la exposición prolongada y sostenida a un agente perturbador, como puede ser un antibiótico, si promueve cambios importantes en la dinámica de las poblaciones a largo plazo [@dethlefsen2011incomplete].

El estudio realizado por David *et al.* (2014) mediante el enfoque de las series temporales, reveló que, en el periodo de viaje durante el cual el sujeto A vio modificado su régimen alimenticio, la dinámica de las poblaciones bacterianas se vio alterada significativamente. Sin embargo, tras dicho periodo, y luego de que el sujeto A retomara su dieta habitual, la dinámica de poblaciones se restableció a un estado similar al registrado previamente al viaje. En contraste, en el sujeto B un fenómeno similar se observó durante el periodo de infección por *Salmonella*, sin embargo, a diferencia del primer caso la dinámica de la microbiota no se recuperó, y se reportó una considerable pérdida de la diversidad [@david2014host].



