--- 
title: "Redes multicapa como herramienta de análisis de la microbiota"
author: "Víctor Lázaro Vidal"
date: "09/02/22"
output:
  word_document: default
  html_document:
    df_print: paged
documentclass: book
bibliography: book.bib
description: |
  Analysis of microbiota patters using multilayer networks.
link-citations: yes
github-repo: rstudio/bookdown-demo
csl: ieee.csl
site: bookdown::bookdown_site
---

# Resumen {-}

En la biología nos vemos constantemente enfrentados a los  sistemas complejos, es decir, sistemas conformados por muchos componentes que interactúan entre sí, y cuyo comportamiento solo puede ser explicado como la suma de la interacción de sus componentes. Un ejemplo de este tipo de sistemas es la microbiota, donde distintos microorganismos interactúan entre sí, con los tejidos del hospedero y con su entorno. Las redes son una herramienta matemática sumamente útil en el análisis de sistemas complejos, sin embargo el enfoque tradicional enfrenta ciertas limitaciones, pues los sistemas biológicos son sistemas dinámicos que cambian en el tiempo y en función de las condiciones. Ante tales retos, las redes multicapa se presentan como un nuevo paradigma en el análisis de sistemas complejos.
 
Empleando redes multiplex, analizamos bases de datos obtenidas a partir de muestras de la microbiota de dos organismos estrechamente relacionados, la solanácea *Datura inoxia* y el escarabajo *Lema daturaphila*. Las redes de coabundancia fueron generadas mediante los algoritmos de inferencia SparCC y ARACNe. Se hallaron comunidades bacterianas involucradas en la fijación de nitrógeno en la capa de la solanácea, mismas que podrían tener una relación mutualista con los tejidos de la planta. Tanto en la solanácea como en el escarabajo se encontraron comunidades bacterianas asociadas al tejido intestinal del insecto, lo que en la solanácea podría derivarse de la materia fecal depositada por las larvas mientras se alimentan de la planta.
 
Bajo el enfoque de las redes temporales, se analizaron datos de dos sujetos que experimentaron cambios en su microbiota derivados de procesos infecciosos. Las redes ARACNe de ambos sujetos mostraron alteraciones en la arquitectura de las redes durante los periodos de disbiosis asociados a procesos infecciosos, lo que podría indicar alteraciones en la dinámica de la microbiota. También se identificaron proporciones alteradas de los *phyla* durante los estadios de disbiosis. Además, gran parte de los nodos encontrados en una misma comunidad eran filogenéticamente cercanos. El uso de redes multicapa nos permitió encontrar patrones en las comunidades bacterianas que podrían estar asociados a procesos puntuales, como la liberación de AGCCs y el metabolismo de determinados nutrientes.

## Summary {-}

In biology, we are constantly facing complex systems. It means systems made up of many components that interact with each other and whose behavior can only be explained as the sum of the interaction of its components. An example of this type of system is the microbiota, where different microorganisms interact with each other, with the host's tissues, and with their environment. Networks are a handy mathematical tool for analyzing complex systems; however, the traditional approach faces certain limitations because biological systems are dynamical systems that change over time and conditions. In order to deal with such challenges, multilayer networks appear as a new paradigm in analyzing complex systems.

Through the use of multiplex networks, I analyzed databases obtained from samples of the microbiota of two closely related organisms: the nightshade *Datura inoxia* and the beetle *Lema daturaphila*. I use SparCC and ARACNe algorithms for inferring co-abundance networks. Bacterial communities involved in nitrogen fixation in the solanaceous layer abound, which could have a mutualistic relationship with plant tissues. Bacterial communities associated with the insect's intestinal tissue appeared on both layers. It could derive from the larvae' dregs in solanaceous while feeding on the plant.

Under the approach of the temporal network, I analyzed data from two subjects who experienced changes in their microbiota derived from infectious processes. The ARACNe networks of both subjects showed alterations in the architecture of the networks during periods of dysbiosis associated with infectious processes, which could indicate alterations in the dynamics of the microbiota. Altered *phyla* proportions came into sight during dysbiosis stages. Furthermore, most of the nodes found in the same community were phylogenetically close. The use of multilayer networks allowed us to find patterns in bacterial communities that could be associated with specific processes, such as the release of SCFAs and the metabolism of certain nutrients.

## Agradecimientos {-}
## Tabla de contenido {-}

1. Resumen
1.1 Summary
1.2 Agradecimientos
1.3 Tabla de contenidos
2. Índice de cuadros y figuras
2.1 Figuras
2.2 Tablas
3. Introducción
4. Objetivo general
4.1 Objetivos particulares
5. Antecedentes
5.1 Definición y generalidades de una red
5.2 Propiedades topológicas de las redes
5.3 Definición y características de las redes multicapa
5.4 Aplicaciones de las redes multicapa
5.5 Inferencias de redes
5.6 La microbiota intestinal y su impacto en la salud humana
5.7 Uso de redes en la exploración de la microbiota
6. Materiales y métodos
7. Resultados
7.1 Resultados de la red escarabajo-solanácea
7.2 Resultados de las redes para los sujetos A y B
8. Discusión
8.1 Discusión de la red escarabajo-solanácea
8.2 Discusión de las redes temporales de los sujetos A y B
8.3 Conclusiones generales
9. Referencias

# Índice de cuadros y figuras {-}

----

## Figuras {-}

**Figura 1:** Red aleatoria y red de mundo pequeño [@schaeffer2007graph].

**Figura 2:** La aleatoriedad de las redes [@watts1998collective].

**Figura 3:** Aleatoriedad de la red vs. longitud de la red [@watts1998collective].

**Figura 4:** Tipos de centralidades [@farahani2019application].

**Figura 5:** Tipos de redes multicapa [@bianconi2018multilayer].

**Figura 6:** Red multiplex de familias florentinas del Renacimiento [@padgett1993robust].

**Figura 7:** Matriz de supra-adyacencia [@cozzo2016multilayer].

**Figura 8:** Coeficiente de clusterización en redes multicapa [@cozzo2013clustering].

**Figura 9:** Análisis de las propiedades de una red multiplex del metro de Zaragoza [@aleta2017multilayer].

**Figura 10:** Red temporal de un modelo SIS [@sanz2014dynamics].

**Figura 11:** Diagrama de interacciones del genoma, epigenoma, transcriptoma, proteoma y metaboloma [@sun2016integrative].

**Figura 12:** Diagrama de interacciones en un ecosistema [@schleuning2020trait].

**Figura 13:** Funcionamiento de los algoritmos de inferencia de redes [@villaintroduction].

**Figura 14:** Inferencia mediante el algoritmo WGCNA [@langfelder2008wgcna].

**Figura 15:** Ejemplo de conexiones directas e indirectas.

**Figura 16:** Curvas PR para algoritmos CRL, ARACNe y MRNet [@meyer2008minet].

**Figura 17:** Comparación entre la inferencia de Pearson y SparCC [@friedman2012inferring].

**Figura 18:** Inferencia de redes por SparCC [@kurtz2015sparse].

**Figura 19:** Discrepancia de la inferencia entre varios algoritmos [@hirano2019difficulty].

**Figura 20:** Interacción entre la microbiota y el huésped bajo distintos regímenes alimenticios [@fan2021gut].

**Figura 21:** Efectos de la disbiosis en el tejido hepático [@del2017gut].

**Figura 22:** Redes de coabundancia de la microbiota de individuos con síntrome de intestino irritable [@smith2013gut].

**Figura 23:** Red multicapa de la microbiota del rumen bovino [@zheng2018improving].

**Figura 24:** Clusterización mediante el método Louvain de las capas de la red escarabajo-solanácea.

**Figura 25:** Red multiplex SparCC de escarabajo-solanácea.

**Figura 26:** Distribución de los *phylum* en las muestras de la red escarabajo-solanácea.

**Figura 27:** Centralidad por *degree* de la red escarabajo-solanácea.

**Figura 28:** Cambio de las abundancias de los nodos entre capas de la red escarabajo-solanácea.

**Figura 29:** Distribución de las abundancias de los *phyla* en el sujeto A a lo largo de las tres capas.

**Figura 30:** Capas de las redes temporales ARACNe de los sujetos A y B.

**Figura 31:** Serie temporal de los diez OTUs más abundantes en las muestras del sujeto A.

## Tablas {-}

**Tabla 1:** Paquetes de R utilizados.

**Tabla 2:** Funciones del paquete ml_BioNets.
